Puppetfile, jenkins_demo/manifests/profile/master.pp
v0.2.7 no long makes copies of ssl related files into the `/etc/nginx`
directory.  This means that when selinux is enabled, the files passed
into the `nginx::resource::vhost` need to have the correct selinux
labels to be read by a http server.
=> fix compatibility with jfryman/nginx v0.2.7

jenkins_demo/manifests/profile/master.pp, jenkins_demo/templates/jobs/dax_webserv-os-matrix/config.xml, jenkins_demo/templates/jobs/qserv-os-matrix/config.xml
Into new jobs named qserv-os-matrix and dax_webserv-os-matrix which are
duplicates of stack-os-matrix but with the "demo" disabled by default.
Note that webserv had not yet been renamed to dax_webserv in
stack-os-matrix.
=> split qserv_distrib & dax_webserv out of stack-os-matrix

jenkins_demo/templates/jobs/dax_webserv-os-matrix/config.xml, jenkins_demo/templates/jobs/qserv-os-matrix/config.xml, jenkins_demo/templates/jobs/stack-os-matrix/config.xml
in the `stack-os-matrix` family of jobs when invoking `lsstswBuild.sh`.
The default branch behavior should be handled internal to `lsst_build`.
=> do not explicity set "master" as the default branch

hieradata/role/master.eyaml
To resolve master<->slave communication issues.  Per the [LTS
Changelog](https://jenkins.io/changelog-stable/), 2.7.3 disabled the new
`JNLP3` protocol, which was the reportedly the cause of widespread
communication issues.
=> bump jenkins version to 2.7.4

jenkins_demo/templates/squash/squash-bokeh@.service.epp
@jhoblitt these changes will be required for the next deployment we basically change the bokeh serve command line to start multiple apps and set a new environment variable SQUASH_BASE_URL used by the apps.
=> Changed way we start the bokeh apps

jenkins_demo/manifests/profile/squash.pp
Per https://docs.djangoproject.com/en/1.8/ref/settings/#secure-proxy-ssl-header
=> set X-Forwarded-Proto header for django

hieradata/role/master.eyaml
bump jenkins matrix-project plugin to 1.10
Fix lost, inaccessible, and/or incorrect links between a parent build and its matrix sub-configurations.
Primary fix: https://github.com/jenkinsci/matrix-project-plugin/pull/41
=> bump jenkins matrix-project plugin to 1.10

hieradata/role/snowflake.yaml, jenkins_demo/manifests/profile/slave.pp
To prevent jobs bound to these labels from running on a snowflake node.
=> remove centos/docker labels from snowflake nodes

jenkins_demo/manifests/profile/master.pp
but allow escape back to / from blueocean by inspecting the referer
header.
=> redirect / to blueocean UI

hieradata/role/master.eyaml
All plugins were updated to their latest with the exception of swarm, which will be handled separately as all working nodes will also need to be updated.
=> update blueocean 1.3.0 + bulk plugin update

hieradata/common.eyaml, hieradata/role/slave.yaml, hieradata/role/snowflake.yaml, jenkins_demo/manifests/role/slave.pp
```
==> el7-6: Error: /Stage[main]/Ruby::Dev/Package[bundler]/ensure: change from absent to latest failed: Could not update: Execution of '/usr/local/rvm/rubies/ruby-2.2.7/bin/gem install --no-rdoc --no-ri bundler' returned 1: Error loading RubyGems plugin "/usr/local/rvm/gems/ruby-2.2.7@global/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by /usr/local/rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/x86_64-linux/openssl.so) - /usr/local/rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/x86_64-linux/openssl.so (LoadError)
==> el7-6: Error loading RubyGems plugin "/usr/local/rvm/gems/ruby-2.2.7@global/gems/gem-wrappers-1.3.2/lib/rubygems_plugin.rb": /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by …
```
=> fix ruby 2.2 openssl 1.0.2 link errors

hieradata/os/RedHat/7.yaml
There are changelog entries that refer to XFS fixes.  This may be
related to the dockerd / XFS timeout errors we are seeing on ec2.
=> bump el7 kernel to 3.10.0-693.11.1.el7.x86_64

hieradata/role/master.eyaml
This is avoid problems with the EUPS installation failing on Linux when
@ is path component.
=> change concurrent build version separator char @ -> _

hieradata/role/master.eyaml, jenkins_demo/manifests/profile/master.pp
The config_hash parameter was being both declared in puppet code and via
hiera resulting in the hiera version being ignored.
=> fix duplicate declaration of jenkins::config_hash

jenkins_demo/manifests/profile/kernel/pquota.pp, jenkins_demo/manifests/role/agent.pp, jenkins_demo/manifests/role/master.pp, terraform/main.tf
Note that the `pquota` flag is discussed in `docker-run(1)` but is absent from https://docs.docker.com/storage/storagedriver/overlayfs-driver/#prerequisites
=> add xfs pquota support to {master,agent} roles

Vagrantfile, hieradata/os/RedHat/7.yaml, jenkins_demo/manifests/profile/jenkins/agent.pp
Previous pinned package versions were no longer available from public centos
mirrors.
=> update default centos AMI + redhat 7 package versions

hieradata/common.eyaml
Updating to tracking the current release -- no major bugfixes:
https://docs.docker.com/release-notes/docker-ce/#stable-releases
=> bump docker to 18.03.1.ce

hieradata/deploy/jenkins-prod.eyaml
No longer used -- replaced by yaml conf in jenkins-dm-jobs.
=> rm prod squash-api-url credentials

tf/ebs_snapshots.tf
Note that vagrant-aws is incapable of setting ebs volume tags upon
instance creation and will require a tag to be manually created in order
for the dlm policy to work.
=> add dlm snapshot lifecycle rules

tf/modules/agent-ldfc/main.tf
This is to prevent load spikes that are reportedly disturbing other loads.
=> set all request == limit; change swarm to 8 cores 
